#include "GLExtension.h"

//[GL_VERSION_1_2]
PFNGLDRAWRANGEELEMENTSPROC		_glDrawRangeElements = nullptr;


//[GL_VERSION_1_3]
PFNGLACTIVETEXTUREPROC			_glActiveTexture = nullptr;


//[GL_VERSION_1_4]
PFNGLMULTIDRAWARRAYSPROC		_glMultiDrawArrays = nullptr;
PFNGLMULTIDRAWELEMENTSPROC		_glMultiDrawElements = nullptr;
PFNGLBLENDCOLORPROC				_glBlendColor = nullptr;
PFNGLBLENDEQUATIONPROC			_glBlendEquation = nullptr;


//[GL_VERSION_1_5]
PFNGLGENQUERIESPROC				_glGenQueries = nullptr;
PFNGLDELETEQUERIESPROC			_glDeleteQueries = nullptr;
PFNGLISQUERYPROC				_glIsQuery = nullptr;
PFNGLBINDBUFFERPROC				_glBindBuffer = nullptr;
PFNGLDELETEBUFFERSPROC			_glDeleteBuffers = nullptr;
PFNGLGENBUFFERSPROC				_glGenBuffers = nullptr;
PFNGLISBUFFERPROC				_glIsBuffer = nullptr;
PFNGLBUFFERDATAPROC				_glBufferData = nullptr;
PFNGLBUFFERSUBDATAPROC			_glBufferSubData = nullptr;
PFNGLGETBUFFERSUBDATAPROC		_glGetBufferSubData = nullptr;
PFNGLMAPBUFFERPROC				_glMapBuffer = nullptr;
PFNGLUNMAPBUFFERPROC			_glUnmapBuffer = nullptr;
PFNGLGETBUFFERPARAMETERIVPROC	_glGetBufferParameteriv = nullptr;
PFNGLGETBUFFERPOINTERVPROC		_glGetBufferPointerv = nullptr;

//[GL_VERSION_2_0]
PFNGLDRAWBUFFERPROC					_glDrawBuffers = nullptr;
PFNGLATTACHSHADERPROC				_glAttachShader = nullptr;
PFNGLBINDATTRIBLOCATIONPROC			_glBindAttribLocation = nullptr;
PFNGLCOMPILESHADERPROC				_glCompileShader = nullptr;
PFNGLCREATEPROGRAMPROC				_glCreateProgram = nullptr;
PFNGLCREATESHADERPROC				_glCreateShader = nullptr;
PFNGLDELETEPROGRAMPROC				_glDeleteProgram = nullptr;
PFNGLDELETESHADERPROC				_glDeleteShader = nullptr;
PFNGLDETACHSHADERPROC				_glDetachShader = nullptr;
PFNGLDISABLEVERTEXATTRIBARRAYPROC	_glDisableVertexAttribArray = nullptr;
PFNGLENABLEVERTEXATTRIBARRAYPROC	_glEnableVertexAttribArray = nullptr;
PFNGLGETACTIVEATTRIBPROC			_glGetActiveAttrib = nullptr;
PFNGLGETACTIVEUNIFORMPROC			_glGetActiveUniform = nullptr;
PFNGLGETATTACHEDSHADERSPROC			_glGetAttachedShaders = nullptr;
PFNGLGETATTRIBLOCATIONPROC			_glGetAttribLocation = nullptr;
PFNGLGETPROGRAMIVPROC				_glGetProgramiv = nullptr;
PFNGLGETPROGRAMINFOLOGPROC			_glGetProgramInfoLog = nullptr;
PFNGLGETSHADERIVPROC				_glGetShaderiv = nullptr;
PFNGLGETSHADERINFOLOGPROC			_glGetShaderInfoLog = nullptr;
PFNGLGETSHADERSOURCEPROC			_glGetShaderSource = nullptr;
PFNGLGETUNIFORMLOCATIONPROC			_glGetUniformLocation = nullptr;
PFNGLGETUNIFORMFVPROC				_glGetUniformfv = nullptr;
PFNGLGETUNIFORMIVPROC				_glGetUniformiv = nullptr;
PFNGLGETVERTEXATTRIBDVPROC			_glGetVertexAttribdv = nullptr;
PFNGLGETVERTEXATTRIBPOINTERVPROC	_glGetVertexAttribPointerv = nullptr;
PFNGLGETVERTEXATTRIBFVPROC			_glGetVertexAttribfv = nullptr;
PFNGLGETVERTEXATTRIBIVPROC			_glGetVertexAttribiv = nullptr;
PFNGLLINKPROGRAMPROC				_glLinkProgram = nullptr;
PFNGLSHADERSOURCEPROC				_glShaderSource = nullptr;
PFNGLUSEPROGRAMPROC					_glUseProgram = nullptr;
PFNGLUNIFORM1FPROC					_glUniform1f = nullptr;
PFNGLUNIFORM2FPROC					_glUniform2f = nullptr;
PFNGLUNIFORM3FPROC					_glUniform3f = nullptr;
PFNGLUNIFORM4FPROC					_glUniform4f = nullptr;
PFNGLUNIFORM1IPROC					_glUniform1i = nullptr;
PFNGLUNIFORM2IPROC					_glUniform2i = nullptr;
PFNGLVERTEXATTRIBPOINTERPROC        _glVertexAttribPointer = nullptr;

//[GL_VERSION_3_0]
PFNGLBINDBUFFERRANGEPROC			_glBindBufferRange = nullptr;
PFNGLBINDBUFFERBASEPROC				_glBindBufferBase = nullptr;
PFNGLGETUNIFORMUIVPROC				_glGetUniformuiv = nullptr;
PFNGLISRENDERBUFFERPROC				_glIsRenderbuffer = nullptr;
PFNGLBINDRENDERBUFFERPROC			_glBindRenderbuffer = nullptr;
PFNGLDELETERENDERBUFFERSPROC		_glDeleteRenderbuffers = nullptr;
PFNGLGENRENDERBUFFERSPROC			_glGenRenderbuffers = nullptr;
PFNGLRENDERBUFFERSTORAGEPROC		_glRenderbufferStorage = nullptr;
PFNGLGETRENDERBUFFERPARAMETERIVPROC	_glGetRenderbufferParameteriv = nullptr;
PFNGLISFRAMEBUFFERPROC				_glIsFramebuffer = nullptr;
PFNGLBINDFRAMEBUFFERPROC			_glBindFramebuffer = nullptr;
PFNGLDELETEFRAMEBUFFERSPROC			_glDeleteFramebuffers = nullptr;
PFNGLGENFRAMEBUFFERSPROC			_glGenFramebuffers = nullptr;
PFNGLCHECKFRAMEBUFFERSTATUSPROC		_glCheckFramebufferStatus = nullptr;
PFNGLFRAMEBUFFERRENDERBUFFERPROC	_glFramebufferRenderbuffer = nullptr;
PFNGLGENERATEMIPMAPPROC				_glGenerateMipmap = nullptr;
PFNGLBLITFRAMEBUFFERPROC			_glBlitFramebuffer = nullptr;
PFNGLBINDVERTEXARRAYPROC			_glBindVertexArray = nullptr;
PFNGLDELETEVERTEXARRAYSPROC			_glDeleteVertexArrays = nullptr;
PFNGLGENVERTEXARRAYSPROC			_glGenVertexArrays = nullptr;
PFNGLMAPBUFFERRANGEPROC				_glMapBufferRange = nullptr;

//[GL_VERSION_3_1]
PFNGLDRAWARRAYSINSTANCEDPROC		_glDrawArraysInstanced = nullptr;
PFNGLDRAWELEMENTSINSTANCEDPROC		_glDrawElementsInstanced = nullptr;
PFNGLTEXBUFFERPROC					_glTexBuffer = nullptr;
PFNGLPRIMITIVERESTARTINDEXPROC		_glPrimitiveRestartIndex = nullptr;
PFNGLCOPYBUFFERSUBDATAPROC			_glCopyBufferSubData = nullptr;

//[GL_VERSION_3_2]
PFNGLFRAMEBUFFERTEXTUREPROC         _glFramebufferTexture = nullptr;

//[GL_VERSION_3_3]
PFNGLGENSAMPLERSPROC				_glGenSamplers = nullptr;
PFNGLDELETESAMPLERSPROC				_glDeleteSamplers = nullptr;
PFNGLISSAMPLERPROC					_glIsSampler = nullptr;
PFNGLBINDSAMPLERPROC				_glBindSampler = nullptr;
PFNGLVERTEXATTRIBDIVISORPROC		_glVertexAttribDivisor = nullptr;

//[GL_VERSION_4_0]
PFNGLDRAWARRAYSINDIRECTPROC			_glDrawArraysIndirect = nullptr;
PFNGLDRAWELEMENTSINDIRECTPROC		_glDrawElementsIndirect = nullptr;

//[GL_VERSION_4_1]
PFNGLRELEASESHADERCOMPILERPROC		_glReleaseShaderCompiler = nullptr;
PFNGLSHADERBINARYPROC				_glShaderBinary = nullptr;
PFNGLGETSHADERPRECISIONFORMATPROC	_glGetShaderPrecisionFormat = nullptr;
PFNGLDEPTHRANGEFPROC				_glDepthRangef = nullptr;
PFNGLCLEARDEPTHFPROC				_glClearDepthf = nullptr;
PFNGLGETPROGRAMBINARYPROC			_glGetProgramBinary = nullptr;
PFNGLPROGRAMBINARYPROC				_glProgramBinary = nullptr;
PFNGLPROGRAMPARAMETERIPROC			_glProgramParameteri = nullptr;
PFNGLUSEPROGRAMSTAGESPROC			_glUseProgramStages = nullptr;
PFNGLACTIVESHADERPROGRAMPROC		_glActiveShaderProgram = nullptr;
PFNGLCREATESHADERPROGRAMVPROC		_glCreateShaderProgramv = nullptr;
PFNGLBINDPROGRAMPIPELINEPROC		_glBindProgramPipeline = nullptr;
PFNGLDELETEPROGRAMPIPELINESPROC		_glDeleteProgramPipelines = nullptr;
PFNGLGENPROGRAMPIPELINESPROC		_glGenProgramPipelines = nullptr;
PFNGLISPROGRAMPIPELINEPROC			_glIsProgramPipeline = nullptr;
PFNGLGETPROGRAMPIPELINEIVPROC		_glGetProgramPipelineiv = nullptr;
PFNGLVALIDATEPROGRAMPIPELINEPROC	_glValidateProgramPipeline = nullptr;
PFNGLGETPROGRAMPIPELINEINFOLOGPROC	_glGetProgramPipelineInfoLog = nullptr;

//[GL_VERSION_4_2]
PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC				_glDrawArraysInstancedBaseInstance = nullptr;
PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC				_glDrawElementsInstancedBaseInstance = nullptr;
PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC	_glDrawElementsInstancedBaseVertexBaseInstance = nullptr;
PFNGLGETINTERNALFORMATIVPROC							_glGetInternalformativ = nullptr;
PFNGLMEMORYBARRIERPROC									_glMemoryBarrier = nullptr;
PFNGLTEXSTORAGE2DPROC									_glTexStorage2D = nullptr;

//[GL_VERSION_4_3]
PFNGLCLEARBUFFERDATAPROC					_glClearBufferData = nullptr;
PFNGLCLEARBUFFERSUBDATAPROC					_glClearBufferSubData = nullptr;
PFNGLDISPATCHCOMPUTEPROC					_glDispatchCompute = nullptr;
PFNGLDISPATCHCOMPUTEINDIRECTPROC			_glDispatchComputeIndirect = nullptr;
PFNGLCOPYIMAGESUBDATAPROC					_glCopyImageSubData = nullptr;
PFNGLFRAMEBUFFERPARAMETERIPROC				_glFramebufferParameteri = nullptr;
PFNGLGETFRAMEBUFFERPARAMETERIVPROC			_glGetFramebufferParameteriv = nullptr;
PFNGLGETINTERNALFORMATI64VPROC				_glGetInternalformati64v = nullptr;
PFNGLINVALIDATETEXSUBIMAGEPROC				_glInvalidateTexSubImage = nullptr;
PFNGLINVALIDATETEXIMAGEPROC					_glInvalidateTexImage = nullptr;
PFNGLINVALIDATEBUFFERSUBDATAPROC			_glInvalidateBufferSubData = nullptr;
PFNGLINVALIDATEBUFFERDATAPROC				_glInvalidateBufferData = nullptr;
PFNGLINVALIDATEFRAMEBUFFERPROC				_glInvalidateFramebuffer = nullptr;
PFNGLINVALIDATESUBFRAMEBUFFERPROC			_glInvalidateSubFramebuffer = nullptr;
PFNGLMULTIDRAWARRAYSINDIRECTPROC			_glMultiDrawArraysIndirect = nullptr;
PFNGLMULTIDRAWELEMENTSINDIRECTPROC			_glMultiDrawElementsIndirect = nullptr;
PFNGLGETPROGRAMINTERFACEIVPROC				_glGetProgramInterfaceiv = nullptr;
PFNGLGETPROGRAMRESOURCEINDEXPROC			_glGetProgramResourceIndex = nullptr;
PFNGLGETPROGRAMRESOURCENAMEPROC				_glGetProgramResourceName = nullptr;
PFNGLGETPROGRAMRESOURCEIVPROC				_glGetProgramResourceiv = nullptr;
PFNGLGETPROGRAMRESOURCELOCATIONPROC			_glGetProgramResourceLocation = nullptr;
PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC	_glGetProgramResourceLocationIndex = nullptr;
PFNGLSHADERSTORAGEBLOCKBINDINGPROC			_glShaderStorageBlockBinding = nullptr;
PFNGLTEXBUFFERRANGEPROC						_glTexBufferRange = nullptr;
PFNGLTEXSTORAGE2DMULTISAMPLEPROC			_glTexStorage2DMultisample = nullptr;
PFNGLTEXSTORAGE3DMULTISAMPLEPROC			_glTexStorage3DMultisample = nullptr;
PFNGLTEXTUREVIEWPROC						_glTextureView = nullptr;
PFNGLBINDVERTEXBUFFERPROC					_glBindVertexBuffer = nullptr;
PFNGLVERTEXATTRIBFORMATPROC					_glVertexAttribFormat = nullptr;
PFNGLVERTEXATTRIBIFORMATPROC				_glVertexAttribIFormat = nullptr;
PFNGLVERTEXATTRIBLFORMATPROC				_glVertexAttribLFormat = nullptr;
PFNGLVERTEXATTRIBBINDINGPROC				_glVertexAttribBinding = nullptr;
PFNGLVERTEXBINDINGDIVISORPROC				_glVertexBindingDivisor = nullptr;
PFNGLDEBUGMESSAGECONTROLPROC				_glDebugMessageControl = nullptr;
PFNGLDEBUGMESSAGEINSERTPROC					_glDebugMessageInsert = nullptr;
PFNGLDEBUGMESSAGECALLBACKPROC				_glDebugMessageCallback = nullptr;
PFNGLGETDEBUGMESSAGELOGPROC					_glGetDebugMessageLog = nullptr;
PFNGLPUSHDEBUGGROUPPROC						_glPushDebugGroup = nullptr;
PFNGLPOPDEBUGGROUPPROC						_glPopDebugGroup = nullptr;
PFNGLOBJECTLABELPROC						_glObjectLabel = nullptr;
PFNGLGETOBJECTLABELPROC						_glGetObjectLabel = nullptr;
PFNGLOBJECTPTRLABELPROC						_glObjectPtrLabel = nullptr;
PFNGLGETOBJECTPTRLABELPROC					_glGetObjectPtrLabel = nullptr;

//[GL_VERSION_4_4]
PFNGLBUFFERSTORAGEPROC			_glBufferStorage = nullptr;
PFNGLCLEARTEXIMAGEPROC			_glClearTexImage = nullptr;
PFNGLCLEARTEXSUBIMAGEPROC 		_glClearTexSubImage = nullptr;
PFNGLBINDBUFFERSBASEPROC		_glBindBuffersBase = nullptr;
PFNGLBINDBUFFERSRANGEPROC 		_glBindBuffersRange = nullptr;
PFNGLBINDTEXTURESPROC			_glBindTextures = nullptr;
PFNGLBINDSAMPLERSPROC			_glBindSamplers = nullptr;
PFNGLBINDIMAGETEXTURESPROC		_glBindImageTextures = nullptr;
PFNGLBINDVERTEXBUFFERSPROC		_glBindVertexBuffers = nullptr;

//[GL_VERSION_4_5]
PFNGLCLIPCONTROLPROC							_glClipControl = nullptr;
PFNGLCREATETRANSFORMFEEDBACKSPROC				_glCreateTransformFeedbacks = nullptr;
PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC			_glTransformFeedbackBufferBase = nullptr;
PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC			_glTransformFeedbackBufferRange = nullptr;
PFNGLGETTRANSFORMFEEDBACKIVPROC					_glGetTransformFeedbackiv = nullptr;
PFNGLGETTRANSFORMFEEDBACKI_VPROC				_glGetTransformFeedbacki_v = nullptr;
PFNGLGETTRANSFORMFEEDBACKI64_VPROC				_glGetTransformFeedbacki64_v = nullptr;
PFNGLCREATEBUFFERSPROC							_glCreateBuffers = nullptr;
PFNGLNAMEDBUFFERSTORAGEPROC						_glNamedBufferStorage = nullptr;
PFNGLNAMEDBUFFERDATAPROC						_glNamedBufferData = nullptr;
PFNGLNAMEDBUFFERSUBDATAPROC						_glNamedBufferSubData = nullptr;
PFNGLCOPYNAMEDBUFFERSUBDATAPROC					_glCopyNamedBufferSubData = nullptr;
PFNGLCLEARNAMEDBUFFERDATAPROC					_glClearNamedBufferData = nullptr;
PFNGLCLEARNAMEDBUFFERSUBDATAPROC				_glClearNamedBufferSubData = nullptr;
PFNGLMAPNAMEDBUFFERPROC							_glMapNamedBuffer = nullptr;
PFNGLMAPNAMEDBUFFERRANGEPROC					_glMapNamedBufferRange = nullptr;
PFNGLUNMAPNAMEDBUFFERPROC						_glUnmapNamedBuffer = nullptr;
PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC			_glFlushMappedNamedBufferRange = nullptr;
PFNGLGETNAMEDBUFFERPARAMETERIVPROC				_glGetNamedBufferParameteriv = nullptr;
PFNGLGETNAMEDBUFFERPARAMETERI64VPROC			_glGetNamedBufferParameteri64v = nullptr;
PFNGLGETNAMEDBUFFERPOINTERVPROC					_glGetNamedBufferPointerv = nullptr;
PFNGLGETNAMEDBUFFERSUBDATAPROC					_glGetNamedBufferSubData = nullptr;
PFNGLCREATEFRAMEBUFFERSPROC						_glCreateFramebuffers = nullptr;
PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC			_glNamedFramebufferRenderbuffer = nullptr;
PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC				_glNamedFramebufferParameteri = nullptr;
PFNGLNAMEDFRAMEBUFFERTEXTUREPROC				_glNamedFramebufferTexture = nullptr;
PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC			_glNamedFramebufferTextureLayer = nullptr;
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC				_glNamedFramebufferDrawBuffer = nullptr;
PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC			_glNamedFramebufferDrawBuffers = nullptr;
PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC				_glNamedFramebufferReadBuffer = nullptr;
PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC			_glInvalidateNamedFramebufferData = nullptr;
PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC		_glInvalidateNamedFramebufferSubData = nullptr;
PFNGLCLEARNAMEDFRAMEBUFFERIVPROC				_glClearNamedFramebufferiv = nullptr;
PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC				_glClearNamedFramebufferuiv = nullptr;
PFNGLCLEARNAMEDFRAMEBUFFERFVPROC				_glClearNamedFramebufferfv = nullptr;
PFNGLCLEARNAMEDFRAMEBUFFERFIPROC				_glClearNamedFramebufferfi = nullptr;
PFNGLBLITNAMEDFRAMEBUFFERPROC					_glBlitNamedFramebuffer = nullptr;
PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC			_glCheckNamedFramebufferStatus = nullptr;
PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC			_glGetNamedFramebufferParameteriv = nullptr;
PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC _glGetNamedFramebufferAttachmentParameteriv = nullptr;
PFNGLCREATERENDERBUFFERSPROC					_glCreateRenderbuffers = nullptr;
PFNGLNAMEDRENDERBUFFERSTORAGEPROC				_glNamedRenderbufferStorage = nullptr;
PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC	_glNamedRenderbufferStorageMultisample = nullptr;
PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC		_glGetNamedRenderbufferParameteriv = nullptr;
PFNGLCREATETEXTURESPROC							_glCreateTextures = nullptr;
PFNGLTEXTUREBUFFERPROC							_glTextureBuffer = nullptr;
PFNGLTEXTUREBUFFERRANGEPROC						_glTextureBufferRange = nullptr;
PFNGLTEXTURESTORAGE1DPROC						_glTextureStorage1D = nullptr;
PFNGLTEXTURESTORAGE2DPROC						_glTextureStorage2D = nullptr;
PFNGLTEXTURESTORAGE3DPROC						_glTextureStorage3D = nullptr;
PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC			_glTextureStorage2DMultisample = nullptr;
PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC			_glTextureStorage3DMultisample = nullptr;
PFNGLTEXTURESUBIMAGE1DPROC						_glTextureSubImage1D = nullptr;
PFNGLTEXTURESUBIMAGE2DPROC						_glTextureSubImage2D = nullptr;
PFNGLTEXTURESUBIMAGE3DPROC						_glTextureSubImage3D = nullptr;
PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC			_glCompressedTextureSubImage1D = nullptr;
PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC			_glCompressedTextureSubImage2D = nullptr;
PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC			_glCompressedTextureSubImage3D = nullptr;
PFNGLCOPYTEXTURESUBIMAGE1DPROC					_glCopyTextureSubImage1D = nullptr;
PFNGLCOPYTEXTURESUBIMAGE2DPROC					_glCopyTextureSubImage2D = nullptr;
PFNGLCOPYTEXTURESUBIMAGE3DPROC					_glCopyTextureSubImage3D = nullptr;
PFNGLTEXTUREPARAMETERFPROC						_glTextureParameterf = nullptr;
PFNGLTEXTUREPARAMETERFVPROC						_glTextureParameterfv = nullptr;
PFNGLTEXTUREPARAMETERIPROC						_glTextureParameteri = nullptr;
PFNGLTEXTUREPARAMETERIIVPROC					_glTextureParameterIiv = nullptr;
PFNGLTEXTUREPARAMETERIUIVPROC					_glTextureParameterIuiv = nullptr;
PFNGLTEXTUREPARAMETERIVPROC						_glTextureParameteriv = nullptr;
PFNGLGENERATETEXTUREMIPMAPPROC					_glGenerateTextureMipmap = nullptr;
PFNGLBINDTEXTUREUNITPROC						_glBindTextureUnit = nullptr;
PFNGLGETTEXTUREIMAGEPROC						_glGetTextureImage = nullptr;
PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC				_glGetCompressedTextureImage = nullptr;
PFNGLGETTEXTURELEVELPARAMETERFVPROC				_glGetTextureLevelParameterfv = nullptr;
PFNGLGETTEXTURELEVELPARAMETERIVPROC				_glGetTextureLevelParameteriv = nullptr;
PFNGLGETTEXTUREPARAMETERFVPROC					_glGetTextureParameterfv = nullptr;
PFNGLGETTEXTUREPARAMETERIIVPROC					_glGetTextureParameterIiv = nullptr;
PFNGLGETTEXTUREPARAMETERIUIVPROC				_glGetTextureParameterIuiv = nullptr;
PFNGLGETTEXTUREPARAMETERIVPROC					_glGetTextureParameteriv = nullptr;
PFNGLCREATEVERTEXARRAYSPROC						_glCreateVertexArrays = nullptr;
PFNGLDISABLEVERTEXARRAYATTRIBPROC				_glDisableVertexArrayAttrib = nullptr;
PFNGLENABLEVERTEXARRAYATTRIBPROC				_glEnableVertexArrayAttrib = nullptr;
PFNGLVERTEXARRAYELEMENTBUFFERPROC				_glVertexArrayElementBuffer = nullptr;
PFNGLVERTEXARRAYVERTEXBUFFERPROC				_glVertexArrayVertexBuffer = nullptr;
PFNGLVERTEXARRAYVERTEXBUFFERSPROC				_glVertexArrayVertexBuffers = nullptr;
PFNGLVERTEXARRAYATTRIBBINDINGPROC				_glVertexArrayAttribBinding = nullptr;
PFNGLVERTEXARRAYATTRIBFORMATPROC				_glVertexArrayAttribFormat = nullptr;
PFNGLVERTEXARRAYATTRIBIFORMATPROC				_glVertexArrayAttribIFormat = nullptr;
PFNGLVERTEXARRAYATTRIBLFORMATPROC				_glVertexArrayAttribLFormat = nullptr;
PFNGLVERTEXARRAYBINDINGDIVISORPROC				_glVertexArrayBindingDivisor = nullptr;
PFNGLGETVERTEXARRAYIVPROC						_glGetVertexArrayiv = nullptr;
PFNGLGETVERTEXARRAYINDEXEDIVPROC				_glGetVertexArrayIndexediv = nullptr;
PFNGLGETVERTEXARRAYINDEXED64IVPROC				_glGetVertexArrayIndexed64iv = nullptr;
PFNGLCREATESAMPLERSPROC							_glCreateSamplers = nullptr;
PFNGLCREATEPROGRAMPIPELINESPROC					_glCreateProgramPipelines = nullptr;
PFNGLCREATEQUERIESPROC							_glCreateQueries = nullptr;
PFNGLGETQUERYBUFFEROBJECTI64VPROC				_glGetQueryBufferObjecti64v = nullptr;
PFNGLGETQUERYBUFFEROBJECTIVPROC					_glGetQueryBufferObjectiv = nullptr;
PFNGLGETQUERYBUFFEROBJECTUI64VPROC				_glGetQueryBufferObjectui64v = nullptr;
PFNGLGETQUERYBUFFEROBJECTUIVPROC				_glGetQueryBufferObjectuiv = nullptr;
PFNGLMEMORYBARRIERBYREGIONPROC					_glMemoryBarrierByRegion = nullptr;
PFNGLGETTEXTURESUBIMAGEPROC						_glGetTextureSubImage = nullptr;
PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC			_glGetCompressedTextureSubImage = nullptr;
PFNGLGETGRAPHICSRESETSTATUSPROC					_glGetGraphicsResetStatus = nullptr;
PFNGLGETNCOMPRESSEDTEXIMAGEPROC					_glGetnCompressedTexImage = nullptr;
PFNGLGETNTEXIMAGEPROC							_glGetnTexImage = nullptr;
PFNGLGETNUNIFORMDVPROC							_glGetnUniformdv = nullptr;
PFNGLGETNUNIFORMFVPROC							_glGetnUniformfv = nullptr;
PFNGLGETNUNIFORMIVPROC							_glGetnUniformiv = nullptr;
PFNGLGETNUNIFORMUIVPROC							_glGetnUniformuiv = nullptr;
PFNGLREADNPIXELSPROC							_glReadnPixels = nullptr;
PFNGLTEXTUREBARRIERPROC							_glTextureBarrier = nullptr;

//[GL_VERSION_4_6]
PFNGLSPECIALIZESHADERPROC				_glSpecializeShader = nullptr;
PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC	_glMultiDrawArraysIndirectCount = nullptr;
PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC	_glMultiDrawElementsIndirectCount = nullptr;
PFNGLPOLYGONOFFSETCLAMPPROC				_glPolygonOffsetClamp = nullptr;

//[WGLEXT]
PFNWGLCHOOSEPIXELFORMATARBPROC			_wglChoosePixelFormatARB = nullptr;
PFNWGLCREATECONTEXTATTRIBSARBPROC       _wglCreateContextAttribsARB = nullptr;
PFNWGLMAKECONTEXTCURRENTARBPROC			_wglMakeContextCurrentARB = nullptr;

void GL::Load_GL_VERSION_1_2()
{
	GL_EXT_PROC(PFNGLDRAWRANGEELEMENTSPROC, glDrawRangeElements);
}

void GL::Load_GL_VERSION_1_3()
{
	GL_EXT_PROC(PFNGLACTIVETEXTUREPROC, glActiveTexture);
}

void GL::Load_GL_VERSION_1_4()
{
	GL_EXT_PROC(PFNGLMULTIDRAWARRAYSPROC, glMultiDrawArrays);
	GL_EXT_PROC(PFNGLMULTIDRAWELEMENTSPROC, glMultiDrawElements);
	GL_EXT_PROC(PFNGLBLENDCOLORPROC, glBlendColor);
	GL_EXT_PROC(PFNGLBLENDEQUATIONPROC, glBlendEquation);
}

void GL::Load_GL_VERSION_1_5()
{
	GL_EXT_PROC(PFNGLGENQUERIESPROC, glGenQueries);
	GL_EXT_PROC(PFNGLDELETEQUERIESPROC, glDeleteQueries);
	GL_EXT_PROC(PFNGLISQUERYPROC, glIsQuery);
	GL_EXT_PROC(PFNGLBINDBUFFERPROC, glBindBuffer);
	GL_EXT_PROC(PFNGLDELETEBUFFERSPROC, glDeleteBuffers);
	GL_EXT_PROC(PFNGLGENBUFFERSPROC, glGenBuffers);
	GL_EXT_PROC(PFNGLISBUFFERPROC, glIsBuffer);
	GL_EXT_PROC(PFNGLBUFFERDATAPROC, glBufferData);
	GL_EXT_PROC(PFNGLBUFFERSUBDATAPROC, glBufferSubData);
	GL_EXT_PROC(PFNGLGETBUFFERSUBDATAPROC, glGetBufferSubData);
	GL_EXT_PROC(PFNGLMAPBUFFERPROC, glMapBuffer);
	GL_EXT_PROC(PFNGLUNMAPBUFFERPROC, glUnmapBuffer);
	GL_EXT_PROC(PFNGLGETBUFFERPARAMETERIVPROC, glGetBufferParameteriv);
	GL_EXT_PROC(PFNGLGETBUFFERPOINTERVPROC, glGetBufferPointerv);
}

void GL::Load_GL_VERSION_2_0()
{
	GL_EXT_PROC(PFNGLDRAWBUFFERPROC, glDrawBuffers);
	GL_EXT_PROC(PFNGLATTACHSHADERPROC, glAttachShader);
	GL_EXT_PROC(PFNGLBINDATTRIBLOCATIONPROC, glBindAttribLocation);
	GL_EXT_PROC(PFNGLCOMPILESHADERPROC, glCompileShader);
	GL_EXT_PROC(PFNGLCREATEPROGRAMPROC, glCreateProgram);
	GL_EXT_PROC(PFNGLCREATESHADERPROC, glCreateShader);
	GL_EXT_PROC(PFNGLDELETEPROGRAMPROC, glDeleteProgram);
	GL_EXT_PROC(PFNGLDELETESHADERPROC, glDeleteShader);
	GL_EXT_PROC(PFNGLDETACHSHADERPROC, glDetachShader);
	GL_EXT_PROC(PFNGLDISABLEVERTEXATTRIBARRAYPROC, glDisableVertexAttribArray);
	GL_EXT_PROC(PFNGLENABLEVERTEXATTRIBARRAYPROC, glEnableVertexAttribArray);
	GL_EXT_PROC(PFNGLGETACTIVEATTRIBPROC, glGetActiveAttrib);
	GL_EXT_PROC(PFNGLGETACTIVEUNIFORMPROC, glGetActiveUniform);
	GL_EXT_PROC(PFNGLGETATTACHEDSHADERSPROC, glGetAttachedShaders);
	GL_EXT_PROC(PFNGLGETATTRIBLOCATIONPROC, glGetAttribLocation);
	GL_EXT_PROC(PFNGLGETPROGRAMIVPROC, glGetProgramiv);
	GL_EXT_PROC(PFNGLGETPROGRAMINFOLOGPROC, glGetProgramInfoLog);
	GL_EXT_PROC(PFNGLGETSHADERIVPROC, glGetShaderiv);
	GL_EXT_PROC(PFNGLGETSHADERINFOLOGPROC, glGetShaderInfoLog);
	GL_EXT_PROC(PFNGLGETSHADERSOURCEPROC, glGetShaderSource);
	GL_EXT_PROC(PFNGLGETUNIFORMLOCATIONPROC, glGetUniformLocation);
	GL_EXT_PROC(PFNGLGETUNIFORMFVPROC, glGetUniformfv);
	GL_EXT_PROC(PFNGLGETUNIFORMIVPROC, glGetUniformiv);
	GL_EXT_PROC(PFNGLGETVERTEXATTRIBDVPROC, glGetVertexAttribdv);
	GL_EXT_PROC(PFNGLGETVERTEXATTRIBPOINTERVPROC, glGetVertexAttribPointerv);
	GL_EXT_PROC(PFNGLGETVERTEXATTRIBFVPROC, glGetVertexAttribfv);
	GL_EXT_PROC(PFNGLGETVERTEXATTRIBIVPROC, glGetVertexAttribiv);
	GL_EXT_PROC(PFNGLLINKPROGRAMPROC, glLinkProgram);
	GL_EXT_PROC(PFNGLSHADERSOURCEPROC, glShaderSource);
	GL_EXT_PROC(PFNGLUSEPROGRAMPROC, glUseProgram);
	GL_EXT_PROC(PFNGLUNIFORM1FPROC, glUniform1f);
	GL_EXT_PROC(PFNGLUNIFORM2FPROC, glUniform2f);
	GL_EXT_PROC(PFNGLUNIFORM3FPROC, glUniform3f);
	GL_EXT_PROC(PFNGLUNIFORM4FPROC, glUniform4f);
	GL_EXT_PROC(PFNGLUNIFORM1IPROC, glUniform1i);
	GL_EXT_PROC(PFNGLUNIFORM2IPROC, glUniform2i);
	GL_EXT_PROC(PFNGLVERTEXATTRIBPOINTERPROC, glVertexAttribPointer);
	
}

void GL::Load_GL_VERSION_3_0()
{
	GL_EXT_PROC(PFNGLBINDBUFFERRANGEPROC, glBindBufferRange);
	GL_EXT_PROC(PFNGLBINDBUFFERBASEPROC, glBindBufferBase);
	GL_EXT_PROC(PFNGLGETUNIFORMUIVPROC, glGetUniformuiv);
	GL_EXT_PROC(PFNGLISRENDERBUFFERPROC, glIsRenderbuffer);
	GL_EXT_PROC(PFNGLBINDRENDERBUFFERPROC, glBindRenderbuffer);
	GL_EXT_PROC(PFNGLDELETERENDERBUFFERSPROC, glDeleteRenderbuffers);
	GL_EXT_PROC(PFNGLGENRENDERBUFFERSPROC, glGenRenderbuffers);
	GL_EXT_PROC(PFNGLRENDERBUFFERSTORAGEPROC, glRenderbufferStorage);
	GL_EXT_PROC(PFNGLGETRENDERBUFFERPARAMETERIVPROC, glGetRenderbufferParameteriv);
	GL_EXT_PROC(PFNGLISFRAMEBUFFERPROC, glIsFramebuffer);
	GL_EXT_PROC(PFNGLBINDFRAMEBUFFERPROC, glBindFramebuffer);
	GL_EXT_PROC(PFNGLDELETEFRAMEBUFFERSPROC, glDeleteFramebuffers);
	GL_EXT_PROC(PFNGLGENFRAMEBUFFERSPROC, glGenFramebuffers);
	GL_EXT_PROC(PFNGLCHECKFRAMEBUFFERSTATUSPROC, glCheckFramebufferStatus);
	GL_EXT_PROC(PFNGLFRAMEBUFFERRENDERBUFFERPROC, glFramebufferRenderbuffer);
	GL_EXT_PROC(PFNGLGENERATEMIPMAPPROC, glGenerateMipmap);
	GL_EXT_PROC(PFNGLBLITFRAMEBUFFERPROC, glBlitFramebuffer);
	GL_EXT_PROC(PFNGLBINDVERTEXARRAYPROC, glBindVertexArray);
	GL_EXT_PROC(PFNGLDELETEVERTEXARRAYSPROC, glDeleteVertexArrays);
	GL_EXT_PROC(PFNGLGENVERTEXARRAYSPROC, glGenVertexArrays);
	GL_EXT_PROC(PFNGLMAPBUFFERRANGEPROC, glMapBufferRange);
}

void GL::Load_GL_VERSION_3_1()
{
	GL_EXT_PROC(PFNGLDRAWARRAYSINSTANCEDPROC, glDrawArraysInstanced);
	GL_EXT_PROC(PFNGLDRAWELEMENTSINSTANCEDPROC, glDrawElementsInstanced);
	GL_EXT_PROC(PFNGLTEXBUFFERPROC, glTexBuffer);
	GL_EXT_PROC(PFNGLPRIMITIVERESTARTINDEXPROC, glPrimitiveRestartIndex);
	GL_EXT_PROC(PFNGLCOPYBUFFERSUBDATAPROC, glCopyBufferSubData);
}

void GL::Load_GL_VERSION_3_2()
{
	GL_EXT_PROC(PFNGLFRAMEBUFFERTEXTUREPROC, glFramebufferTexture);
}

void GL::Load_GL_VERSION_3_3()
{
	GL_EXT_PROC(PFNGLGENSAMPLERSPROC, glGenSamplers);
	GL_EXT_PROC(PFNGLDELETESAMPLERSPROC, glDeleteSamplers);
	GL_EXT_PROC(PFNGLISSAMPLERPROC, glIsSampler);
	GL_EXT_PROC(PFNGLBINDSAMPLERPROC, glBindSampler);
	GL_EXT_PROC(PFNGLVERTEXATTRIBDIVISORPROC, glVertexAttribDivisor);
}

void GL::Load_GL_VERSION_4_0()
{
	GL_EXT_PROC(PFNGLDRAWARRAYSINDIRECTPROC, glDrawArraysIndirect);
	GL_EXT_PROC(PFNGLDRAWELEMENTSINDIRECTPROC, glDrawElementsIndirect);
}

void GL::Load_GL_VERSION_4_1()
{
	GL_EXT_PROC(PFNGLRELEASESHADERCOMPILERPROC, glReleaseShaderCompiler);
	GL_EXT_PROC(PFNGLSHADERBINARYPROC, glShaderBinary);
	GL_EXT_PROC(PFNGLGETSHADERPRECISIONFORMATPROC, glGetShaderPrecisionFormat);
	GL_EXT_PROC(PFNGLDEPTHRANGEFPROC, glDepthRangef);
	GL_EXT_PROC(PFNGLCLEARDEPTHFPROC, glClearDepthf);
	GL_EXT_PROC(PFNGLGETPROGRAMBINARYPROC, glGetProgramBinary);
	GL_EXT_PROC(PFNGLPROGRAMBINARYPROC, glProgramBinary);
	GL_EXT_PROC(PFNGLPROGRAMPARAMETERIPROC, glProgramParameteri);
	GL_EXT_PROC(PFNGLUSEPROGRAMSTAGESPROC, glUseProgramStages);
	GL_EXT_PROC(PFNGLACTIVESHADERPROGRAMPROC, glActiveShaderProgram);
	GL_EXT_PROC(PFNGLCREATESHADERPROGRAMVPROC, glCreateShaderProgramv);
	GL_EXT_PROC(PFNGLBINDPROGRAMPIPELINEPROC, glBindProgramPipeline);
	GL_EXT_PROC(PFNGLDELETEPROGRAMPIPELINESPROC, glDeleteProgramPipelines);
	GL_EXT_PROC(PFNGLGENPROGRAMPIPELINESPROC, glGenProgramPipelines);
	GL_EXT_PROC(PFNGLISPROGRAMPIPELINEPROC, glIsProgramPipeline);
	GL_EXT_PROC(PFNGLGETPROGRAMPIPELINEIVPROC, glGetProgramPipelineiv);
	GL_EXT_PROC(PFNGLVALIDATEPROGRAMPIPELINEPROC, glValidateProgramPipeline);
	GL_EXT_PROC(PFNGLGETPROGRAMPIPELINEINFOLOGPROC, glGetProgramPipelineInfoLog);
}

void GL::Load_GL_VERSION_4_2()
{
	GL_EXT_PROC(PFNGLDRAWARRAYSINSTANCEDBASEINSTANCEPROC, glDrawArraysInstancedBaseInstance);
	GL_EXT_PROC(PFNGLDRAWELEMENTSINSTANCEDBASEINSTANCEPROC, glDrawElementsInstancedBaseInstance);
	GL_EXT_PROC(PFNGLDRAWELEMENTSINSTANCEDBASEVERTEXBASEINSTANCEPROC, glDrawElementsInstancedBaseVertexBaseInstance);
	GL_EXT_PROC(PFNGLGETINTERNALFORMATIVPROC, glGetInternalformativ);
	GL_EXT_PROC(PFNGLMEMORYBARRIERPROC, glMemoryBarrier);
	GL_EXT_PROC(PFNGLTEXSTORAGE2DPROC, glTexStorage2D);
}

void GL::Load_GL_VERSION_4_3()
{
	GL_EXT_PROC(PFNGLCLEARBUFFERDATAPROC, glClearBufferData);
	GL_EXT_PROC(PFNGLCLEARBUFFERSUBDATAPROC, glClearBufferSubData);
	GL_EXT_PROC(PFNGLDISPATCHCOMPUTEPROC, glDispatchCompute);
	GL_EXT_PROC(PFNGLDISPATCHCOMPUTEINDIRECTPROC, glDispatchComputeIndirect);
	GL_EXT_PROC(PFNGLCOPYIMAGESUBDATAPROC, glCopyImageSubData);
	GL_EXT_PROC(PFNGLFRAMEBUFFERPARAMETERIPROC, glFramebufferParameteri);
	GL_EXT_PROC(PFNGLGETFRAMEBUFFERPARAMETERIVPROC, glGetFramebufferParameteriv);
	GL_EXT_PROC(PFNGLGETINTERNALFORMATI64VPROC, glGetInternalformati64v);
	GL_EXT_PROC(PFNGLINVALIDATETEXSUBIMAGEPROC, glInvalidateTexSubImage);
	GL_EXT_PROC(PFNGLINVALIDATETEXIMAGEPROC, glInvalidateTexImage);
	GL_EXT_PROC(PFNGLINVALIDATEBUFFERSUBDATAPROC, glInvalidateBufferSubData);
	GL_EXT_PROC(PFNGLINVALIDATEBUFFERDATAPROC, glInvalidateBufferData);
	GL_EXT_PROC(PFNGLINVALIDATEFRAMEBUFFERPROC, glInvalidateFramebuffer);
	GL_EXT_PROC(PFNGLINVALIDATESUBFRAMEBUFFERPROC, glInvalidateSubFramebuffer);
	GL_EXT_PROC(PFNGLMULTIDRAWARRAYSINDIRECTPROC, glMultiDrawArraysIndirect);
	GL_EXT_PROC(PFNGLMULTIDRAWELEMENTSINDIRECTPROC, glMultiDrawElementsIndirect);
	GL_EXT_PROC(PFNGLGETPROGRAMINTERFACEIVPROC, glGetProgramInterfaceiv);
	GL_EXT_PROC(PFNGLGETPROGRAMRESOURCEINDEXPROC, glGetProgramResourceIndex);
	GL_EXT_PROC(PFNGLGETPROGRAMRESOURCENAMEPROC, glGetProgramResourceName);
	GL_EXT_PROC(PFNGLGETPROGRAMRESOURCEIVPROC, glGetProgramResourceiv);
	GL_EXT_PROC(PFNGLGETPROGRAMRESOURCELOCATIONPROC, glGetProgramResourceLocation);
	GL_EXT_PROC(PFNGLGETPROGRAMRESOURCELOCATIONINDEXPROC, glGetProgramResourceLocationIndex);
	GL_EXT_PROC(PFNGLSHADERSTORAGEBLOCKBINDINGPROC, glShaderStorageBlockBinding);
	GL_EXT_PROC(PFNGLTEXBUFFERRANGEPROC, glTexBufferRange);
	GL_EXT_PROC(PFNGLTEXSTORAGE2DMULTISAMPLEPROC, glTexStorage2DMultisample);
	GL_EXT_PROC(PFNGLTEXSTORAGE3DMULTISAMPLEPROC, glTexStorage3DMultisample);
	GL_EXT_PROC(PFNGLTEXTUREVIEWPROC, glTextureView);
	GL_EXT_PROC(PFNGLBINDVERTEXBUFFERPROC, glBindVertexBuffer);
	GL_EXT_PROC(PFNGLVERTEXATTRIBFORMATPROC, glVertexAttribFormat);
	GL_EXT_PROC(PFNGLVERTEXATTRIBIFORMATPROC, glVertexAttribIFormat);
	GL_EXT_PROC(PFNGLVERTEXATTRIBLFORMATPROC, glVertexAttribLFormat);
	GL_EXT_PROC(PFNGLVERTEXATTRIBBINDINGPROC, glVertexAttribBinding);
	GL_EXT_PROC(PFNGLVERTEXBINDINGDIVISORPROC, glVertexBindingDivisor);
	GL_EXT_PROC(PFNGLDEBUGMESSAGECONTROLPROC, glDebugMessageControl);
	GL_EXT_PROC(PFNGLDEBUGMESSAGEINSERTPROC, glDebugMessageInsert);
	GL_EXT_PROC(PFNGLDEBUGMESSAGECALLBACKPROC, glDebugMessageCallback);
	GL_EXT_PROC(PFNGLGETDEBUGMESSAGELOGPROC, glGetDebugMessageLog);
	GL_EXT_PROC(PFNGLPUSHDEBUGGROUPPROC, glPushDebugGroup);
	GL_EXT_PROC(PFNGLPOPDEBUGGROUPPROC, glPopDebugGroup);
	GL_EXT_PROC(PFNGLOBJECTLABELPROC, glObjectLabel);
	GL_EXT_PROC(PFNGLGETOBJECTLABELPROC, glGetObjectLabel);
	GL_EXT_PROC(PFNGLOBJECTPTRLABELPROC, glObjectPtrLabel);
	GL_EXT_PROC(PFNGLGETOBJECTPTRLABELPROC, glGetObjectPtrLabel);
}

void GL::Load_GL_VERSION_4_4()
{
	GL_EXT_PROC(PFNGLBUFFERSTORAGEPROC, glBufferStorage);
	GL_EXT_PROC(PFNGLCLEARTEXIMAGEPROC, glClearTexImage);
	GL_EXT_PROC(PFNGLCLEARTEXSUBIMAGEPROC, glClearTexSubImage);
	GL_EXT_PROC(PFNGLBINDBUFFERSBASEPROC, glBindBuffersBase);
	GL_EXT_PROC(PFNGLBINDBUFFERSRANGEPROC, glBindBuffersRange);
	GL_EXT_PROC(PFNGLBINDTEXTURESPROC, glBindTextures);
	GL_EXT_PROC(PFNGLBINDSAMPLERSPROC, glBindSamplers);
	GL_EXT_PROC(PFNGLBINDIMAGETEXTURESPROC, glBindImageTextures);
	GL_EXT_PROC(PFNGLBINDVERTEXBUFFERSPROC, glBindVertexBuffers);
}

void GL::Load_GL_VERSION_4_5()
{
	GL_EXT_PROC(PFNGLCLIPCONTROLPROC, glClipControl);
	GL_EXT_PROC(PFNGLCREATETRANSFORMFEEDBACKSPROC, glCreateTransformFeedbacks);
	GL_EXT_PROC(PFNGLTRANSFORMFEEDBACKBUFFERBASEPROC, glTransformFeedbackBufferBase);
	GL_EXT_PROC(PFNGLTRANSFORMFEEDBACKBUFFERRANGEPROC, glTransformFeedbackBufferRange);
	GL_EXT_PROC(PFNGLGETTRANSFORMFEEDBACKIVPROC, glGetTransformFeedbackiv);
	GL_EXT_PROC(PFNGLGETTRANSFORMFEEDBACKI_VPROC, glGetTransformFeedbacki_v);
	GL_EXT_PROC(PFNGLGETTRANSFORMFEEDBACKI64_VPROC, glGetTransformFeedbacki64_v);
	GL_EXT_PROC(PFNGLCREATEBUFFERSPROC, glCreateBuffers);
	GL_EXT_PROC(PFNGLNAMEDBUFFERSTORAGEPROC, glNamedBufferStorage);
	GL_EXT_PROC(PFNGLNAMEDBUFFERDATAPROC, glNamedBufferData);
	GL_EXT_PROC(PFNGLNAMEDBUFFERSUBDATAPROC, glNamedBufferSubData);
	GL_EXT_PROC(PFNGLCOPYNAMEDBUFFERSUBDATAPROC, glCopyNamedBufferSubData);
	GL_EXT_PROC(PFNGLCLEARNAMEDBUFFERDATAPROC, glClearNamedBufferData);
	GL_EXT_PROC(PFNGLCLEARNAMEDBUFFERSUBDATAPROC, glClearNamedBufferSubData);
	GL_EXT_PROC(PFNGLMAPNAMEDBUFFERPROC, glMapNamedBuffer);
	GL_EXT_PROC(PFNGLMAPNAMEDBUFFERRANGEPROC, glMapNamedBufferRange);
	GL_EXT_PROC(PFNGLUNMAPNAMEDBUFFERPROC, glUnmapNamedBuffer);
	GL_EXT_PROC(PFNGLFLUSHMAPPEDNAMEDBUFFERRANGEPROC, glFlushMappedNamedBufferRange);
	GL_EXT_PROC(PFNGLGETNAMEDBUFFERPARAMETERIVPROC, glGetNamedBufferParameteriv);
	GL_EXT_PROC(PFNGLGETNAMEDBUFFERPARAMETERI64VPROC, glGetNamedBufferParameteri64v);
	GL_EXT_PROC(PFNGLGETNAMEDBUFFERPOINTERVPROC, glGetNamedBufferPointerv);
	GL_EXT_PROC(PFNGLGETNAMEDBUFFERSUBDATAPROC, glGetNamedBufferSubData);
	GL_EXT_PROC(PFNGLCREATEFRAMEBUFFERSPROC, glCreateFramebuffers);
	GL_EXT_PROC(PFNGLNAMEDFRAMEBUFFERRENDERBUFFERPROC, glNamedFramebufferRenderbuffer);
	GL_EXT_PROC(PFNGLNAMEDFRAMEBUFFERPARAMETERIPROC, glNamedFramebufferParameteri);
	GL_EXT_PROC(PFNGLNAMEDFRAMEBUFFERTEXTUREPROC, glNamedFramebufferTexture);
	GL_EXT_PROC(PFNGLNAMEDFRAMEBUFFERTEXTURELAYERPROC, glNamedFramebufferTextureLayer);
	GL_EXT_PROC(PFNGLNAMEDFRAMEBUFFERDRAWBUFFERPROC, glNamedFramebufferDrawBuffer);
	GL_EXT_PROC(PFNGLNAMEDFRAMEBUFFERDRAWBUFFERSPROC, glNamedFramebufferDrawBuffers);
	GL_EXT_PROC(PFNGLNAMEDFRAMEBUFFERREADBUFFERPROC, glNamedFramebufferReadBuffer);
	GL_EXT_PROC(PFNGLINVALIDATENAMEDFRAMEBUFFERDATAPROC, glInvalidateNamedFramebufferData);
	GL_EXT_PROC(PFNGLINVALIDATENAMEDFRAMEBUFFERSUBDATAPROC, glInvalidateNamedFramebufferSubData);
	GL_EXT_PROC(PFNGLCLEARNAMEDFRAMEBUFFERIVPROC, glClearNamedFramebufferiv);
	GL_EXT_PROC(PFNGLCLEARNAMEDFRAMEBUFFERUIVPROC, glClearNamedFramebufferuiv);
	GL_EXT_PROC(PFNGLCLEARNAMEDFRAMEBUFFERFVPROC, glClearNamedFramebufferfv);
	GL_EXT_PROC(PFNGLCLEARNAMEDFRAMEBUFFERFIPROC, glClearNamedFramebufferfi);
	GL_EXT_PROC(PFNGLBLITNAMEDFRAMEBUFFERPROC, glBlitNamedFramebuffer);
	GL_EXT_PROC(PFNGLCHECKNAMEDFRAMEBUFFERSTATUSPROC, glCheckNamedFramebufferStatus);
	GL_EXT_PROC(PFNGLGETNAMEDFRAMEBUFFERPARAMETERIVPROC, glGetNamedFramebufferParameteriv);
	GL_EXT_PROC(PFNGLGETNAMEDFRAMEBUFFERATTACHMENTPARAMETERIVPROC, glGetNamedFramebufferAttachmentParameteriv);
	GL_EXT_PROC(PFNGLCREATERENDERBUFFERSPROC, glCreateRenderbuffers);
	GL_EXT_PROC(PFNGLNAMEDRENDERBUFFERSTORAGEPROC, glNamedRenderbufferStorage);
	GL_EXT_PROC(PFNGLNAMEDRENDERBUFFERSTORAGEMULTISAMPLEPROC, glNamedRenderbufferStorageMultisample);
	GL_EXT_PROC(PFNGLGETNAMEDRENDERBUFFERPARAMETERIVPROC, glGetNamedRenderbufferParameteriv);
	GL_EXT_PROC(PFNGLCREATETEXTURESPROC, glCreateTextures);
	GL_EXT_PROC(PFNGLTEXTUREBUFFERPROC, glTextureBuffer);
	GL_EXT_PROC(PFNGLTEXTUREBUFFERRANGEPROC, glTextureBufferRange);
	GL_EXT_PROC(PFNGLTEXTURESTORAGE1DPROC, glTextureStorage1D);
	GL_EXT_PROC(PFNGLTEXTURESTORAGE2DPROC, glTextureStorage2D);
	GL_EXT_PROC(PFNGLTEXTURESTORAGE3DPROC, glTextureStorage3D);
	GL_EXT_PROC(PFNGLTEXTURESTORAGE2DMULTISAMPLEPROC, glTextureStorage2DMultisample);
	GL_EXT_PROC(PFNGLTEXTURESTORAGE3DMULTISAMPLEPROC, glTextureStorage3DMultisample);
	GL_EXT_PROC(PFNGLTEXTURESUBIMAGE1DPROC, glTextureSubImage1D);
	GL_EXT_PROC(PFNGLTEXTURESUBIMAGE2DPROC, glTextureSubImage2D);
	GL_EXT_PROC(PFNGLTEXTURESUBIMAGE3DPROC, glTextureSubImage3D);
	GL_EXT_PROC(PFNGLCOMPRESSEDTEXTURESUBIMAGE1DPROC, glCompressedTextureSubImage1D);
	GL_EXT_PROC(PFNGLCOMPRESSEDTEXTURESUBIMAGE2DPROC, glCompressedTextureSubImage2D);
	GL_EXT_PROC(PFNGLCOMPRESSEDTEXTURESUBIMAGE3DPROC, glCompressedTextureSubImage3D);
	GL_EXT_PROC(PFNGLCOPYTEXTURESUBIMAGE1DPROC, glCopyTextureSubImage1D);
	GL_EXT_PROC(PFNGLCOPYTEXTURESUBIMAGE2DPROC, glCopyTextureSubImage2D);
	GL_EXT_PROC(PFNGLCOPYTEXTURESUBIMAGE3DPROC, glCopyTextureSubImage3D);
	GL_EXT_PROC(PFNGLTEXTUREPARAMETERFPROC, glTextureParameterf);
	GL_EXT_PROC(PFNGLTEXTUREPARAMETERFVPROC, glTextureParameterfv);
	GL_EXT_PROC(PFNGLTEXTUREPARAMETERIPROC, glTextureParameteri);
	GL_EXT_PROC(PFNGLTEXTUREPARAMETERIIVPROC, glTextureParameterIiv);
	GL_EXT_PROC(PFNGLTEXTUREPARAMETERIUIVPROC, glTextureParameterIuiv);
	GL_EXT_PROC(PFNGLTEXTUREPARAMETERIVPROC, glTextureParameteriv);
	GL_EXT_PROC(PFNGLGENERATETEXTUREMIPMAPPROC, glGenerateTextureMipmap);
	GL_EXT_PROC(PFNGLBINDTEXTUREUNITPROC, glBindTextureUnit);
	GL_EXT_PROC(PFNGLGETTEXTUREIMAGEPROC, glGetTextureImage);
	GL_EXT_PROC(PFNGLGETCOMPRESSEDTEXTUREIMAGEPROC, glGetCompressedTextureImage);
	GL_EXT_PROC(PFNGLGETTEXTURELEVELPARAMETERFVPROC, glGetTextureLevelParameterfv);
	GL_EXT_PROC(PFNGLGETTEXTURELEVELPARAMETERIVPROC, glGetTextureLevelParameteriv);
	GL_EXT_PROC(PFNGLGETTEXTUREPARAMETERFVPROC, glGetTextureParameterfv);
	GL_EXT_PROC(PFNGLGETTEXTUREPARAMETERIIVPROC, glGetTextureParameterIiv);
	GL_EXT_PROC(PFNGLGETTEXTUREPARAMETERIUIVPROC, glGetTextureParameterIuiv);
	GL_EXT_PROC(PFNGLGETTEXTUREPARAMETERIVPROC, glGetTextureParameteriv);
	GL_EXT_PROC(PFNGLCREATEVERTEXARRAYSPROC, glCreateVertexArrays);
	GL_EXT_PROC(PFNGLDISABLEVERTEXARRAYATTRIBPROC, glDisableVertexArrayAttrib);
	GL_EXT_PROC(PFNGLENABLEVERTEXARRAYATTRIBPROC, glEnableVertexArrayAttrib);
	GL_EXT_PROC(PFNGLVERTEXARRAYELEMENTBUFFERPROC, glVertexArrayElementBuffer);
	GL_EXT_PROC(PFNGLVERTEXARRAYVERTEXBUFFERPROC, glVertexArrayVertexBuffer);
	GL_EXT_PROC(PFNGLVERTEXARRAYVERTEXBUFFERSPROC, glVertexArrayVertexBuffers);
	GL_EXT_PROC(PFNGLVERTEXARRAYATTRIBBINDINGPROC, glVertexArrayAttribBinding);
	GL_EXT_PROC(PFNGLVERTEXARRAYATTRIBFORMATPROC, glVertexArrayAttribFormat);
	GL_EXT_PROC(PFNGLVERTEXARRAYATTRIBIFORMATPROC, glVertexArrayAttribIFormat);
	GL_EXT_PROC(PFNGLVERTEXARRAYATTRIBLFORMATPROC, glVertexArrayAttribLFormat);
	GL_EXT_PROC(PFNGLVERTEXARRAYBINDINGDIVISORPROC, glVertexArrayBindingDivisor);
	GL_EXT_PROC(PFNGLGETVERTEXARRAYIVPROC, glGetVertexArrayiv);
	GL_EXT_PROC(PFNGLGETVERTEXARRAYINDEXEDIVPROC, glGetVertexArrayIndexediv);
	GL_EXT_PROC(PFNGLGETVERTEXARRAYINDEXED64IVPROC, glGetVertexArrayIndexed64iv);
	GL_EXT_PROC(PFNGLCREATESAMPLERSPROC, glCreateSamplers);
	GL_EXT_PROC(PFNGLCREATEPROGRAMPIPELINESPROC, glCreateProgramPipelines);
	GL_EXT_PROC(PFNGLCREATEQUERIESPROC, glCreateQueries);
	GL_EXT_PROC(PFNGLGETQUERYBUFFEROBJECTI64VPROC, glGetQueryBufferObjecti64v);
	GL_EXT_PROC(PFNGLGETQUERYBUFFEROBJECTIVPROC, glGetQueryBufferObjectiv);
	GL_EXT_PROC(PFNGLGETQUERYBUFFEROBJECTUI64VPROC, glGetQueryBufferObjectui64v);
	GL_EXT_PROC(PFNGLGETQUERYBUFFEROBJECTUIVPROC, glGetQueryBufferObjectuiv);
	GL_EXT_PROC(PFNGLMEMORYBARRIERBYREGIONPROC, glMemoryBarrierByRegion);
	GL_EXT_PROC(PFNGLGETTEXTURESUBIMAGEPROC, glGetTextureSubImage);
	GL_EXT_PROC(PFNGLGETCOMPRESSEDTEXTURESUBIMAGEPROC, glGetCompressedTextureSubImage);
	GL_EXT_PROC(PFNGLGETGRAPHICSRESETSTATUSPROC, glGetGraphicsResetStatus);
	GL_EXT_PROC(PFNGLGETNCOMPRESSEDTEXIMAGEPROC, glGetnCompressedTexImage);
	GL_EXT_PROC(PFNGLGETNTEXIMAGEPROC, glGetnTexImage);
	GL_EXT_PROC(PFNGLGETNUNIFORMDVPROC, glGetnUniformdv);
	GL_EXT_PROC(PFNGLGETNUNIFORMFVPROC, glGetnUniformfv);
	GL_EXT_PROC(PFNGLGETNUNIFORMIVPROC, glGetnUniformiv);
	GL_EXT_PROC(PFNGLGETNUNIFORMUIVPROC, glGetnUniformuiv);
	GL_EXT_PROC(PFNGLREADNPIXELSPROC, glReadnPixels);
	GL_EXT_PROC(PFNGLTEXTUREBARRIERPROC, glTextureBarrier);
}

void GL::Load_GL_VERSION_4_6()
{
	GL_EXT_PROC(PFNGLSPECIALIZESHADERPROC, glSpecializeShader);
	GL_EXT_PROC(PFNGLMULTIDRAWARRAYSINDIRECTCOUNTPROC, glMultiDrawArraysIndirectCount);
	GL_EXT_PROC(PFNGLMULTIDRAWELEMENTSINDIRECTCOUNTPROC, glMultiDrawElementsIndirectCount);
	GL_EXT_PROC(PFNGLPOLYGONOFFSETCLAMPPROC, glPolygonOffsetClamp);
}

void GL::Load_WGLEXT()
{
	//[WGLEXT]
	GL_EXT_PROC(PFNWGLCHOOSEPIXELFORMATARBPROC, wglChoosePixelFormatARB);
	GL_EXT_PROC(PFNWGLCREATECONTEXTATTRIBSARBPROC, wglCreateContextAttribsARB);
	GL_EXT_PROC(PFNWGLMAKECONTEXTCURRENTARBPROC, wglMakeContextCurrentARB);
}

void GL::LoadGLExtension()
{
	HWND hwnd = CreateWindowEx(NULL, "STATIC", "", NULL, 0, 0,
		0, 0, NULL, NULL, GetModuleHandle(NULL), NULL);

	HDC dc = GetDC(hwnd);

	PIXELFORMATDESCRIPTOR pfd{};
	pfd.nSize = sizeof(PIXELFORMATDESCRIPTOR);
	pfd.nVersion = 1;
	pfd.dwFlags = PFD_DOUBLEBUFFER | PFD_SUPPORT_OPENGL | PFD_DRAW_TO_WINDOW;
	pfd.iPixelType = PFD_TYPE_RGBA;
	pfd.cColorBits = 32;
	pfd.cDepthBits = 24;
	pfd.cAlphaBits = 8;
	pfd.cStencilBits = 8;
	pfd.iLayerType = PFD_MAIN_PLANE;

	int pixelFormat = ::ChoosePixelFormat(dc, &pfd);
	SetPixelFormat(dc, pixelFormat, &pfd);
	HGLRC rc = wglCreateContext(dc);
	wglMakeCurrent(dc, rc);

	Load_GL_VERSION_1_2();
	Load_GL_VERSION_1_3();
	Load_GL_VERSION_1_4();
	Load_GL_VERSION_1_5();
	Load_GL_VERSION_2_0();
	Load_GL_VERSION_3_0();
	Load_GL_VERSION_4_0();
	Load_GL_VERSION_4_1();
	Load_GL_VERSION_4_2();
	Load_GL_VERSION_4_3();
	Load_GL_VERSION_4_4();
	Load_GL_VERSION_4_5();
	Load_GL_VERSION_4_6();
	Load_WGLEXT();

	wglMakeCurrent(NULL, NULL);
	wglDeleteContext(rc);
	ReleaseDC(hwnd, dc);
	DestroyWindow(hwnd);
}
